const UserModel = require('../models/UserModel')
const ChatModel = require("../models/ChatModel")
const MessageModel = require("../models/MessageModel")
const { BadRequestError, NotFoundError } = require('../middleware/errors/httpErrors')
const {notifyUser} = require('../utils/NotificationService')